[package]
name = "burrito"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
auto_ops = "0.3.0"
gc = { version = "0.4.1", features = ["derive"] }

[build-dependencies]
bindgen = "0.63.0"